### ISSUE TITLE
One-step prediction performance

### ISSUE THREAD

**Issue by hammer-wang** [sjblim/rmsn_nips_2018#1]
Hi Bryan, 

Thanks for sharing the code. Very nice work! 

I'm trying to reproduce the one-step prediction results in your paper. I'd appreciate it a lot if you could help me understand your model.

In my understanding, the one-step prediction results (i.e. figure 4 in your NeurIPS paper) are obtained from the encoder and the decoder is not necessary to reproduce the results. Is this correct? 

I downloaded your code and ran with the provided hyperparameter to test the encoder performance. However, my results show that the normalized RMSE increases as the confounding coefficient decreases to 0. Here is my result:

![image](https://user-images.githubusercontent.com/17487320/55578868-ecfc4a00-56e4-11e9-80e6-eae3e8467b0a.png)

Do you have any idea why this may happen? I'm attaching the hyperparameters I used here (same as what were provided in the original code)

![image](https://user-images.githubusercontent.com/17487320/55578946-17e69e00-56e5-11e9-8109-f11dd528e63c.png)

Thanks a lot and looking forward to your feedback!

Best,
Haozhu

**Comment by sjblim** [comment]
Hi Haozhu,

Thanks for getting in touch. I was wondering if you might be running the
latest code by any chance?

Unfortunately, it does seem like the hyperparameters are a little sensitive
to the actual dataset used, but the latest version now has a batch file
(test_rmsn.bat or test_rmsn.sh) which runs the entire hyperparameter
optimisation procedure.

With this, I've also reproduced a similar set of results to the original
paper - see below for one-step predictions:

[image: image.png]

Thanks,
Bryan
*--*
*Bryan Lim*

**Comment by hammer-wang** [comment]
Hi Bryan,

Thanks for your quick reply! I'll try to run the entire optimization process. Is it true that the one-step prediction is made by the encoder? 

Btw, the image you attached does not show (see below). Could you please upload it again? Appreciate that! 

![image](https://user-images.githubusercontent.com/17487320/55583725-985ecc00-56f0-11e9-92ee-1597653eb6f0.png)

Thanks,
Haozhu

**Comment by sjblim** [comment]
Yup that should be the output from the encoder itself. Also reattaching the chart below:

![image](https://user-images.githubusercontent.com/3411074/55621968-e3331f00-5796-11e9-8950-ee4ff8c1dbb3.png)
